export const GarmentSizes = [
  {
    size_name: "Standard",
    size_unit: "cm",
    chest_min: 93,
    chest_max: 100,
    waist_min: 81,
    waist_max: 88,
    hip_min: 92,
    hip_max: 99,
    sleeve_length_min: 20,
    sleeve_length_max: 21,
    body_length_min: 68,
    body_length_max: 70,
  },
  {
    size_name: "XS",
    size_unit: "cm",
    chest_min: 83,
    chest_max: 86,
    waist_min: 71,
    waist_max: 74,
    hip_min: 82,
    hip_max: 85,
    sleeve_length_min: 20,
    sleeve_length_max: 21,
    body_length_min: 66,
    body_length_max: 68,
  },
  {
    size_name: "S",
    size_unit: "cm",
    chest_min: 87,
    chest_max: 92,
    waist_min: 75,
    waist_max: 80,
    hip_min: 86,
    hip_max: 91,
    sleeve_length_min: 20,
    sleeve_length_max: 21,
    body_length_min: 67,
    body_length_max: 69,
  },
  {
    size_name: "M",
    size_unit: "cm",
    chest_min: 93,
    chest_max: 100,
    waist_min: 81,
    waist_max: 88,
    hip_min: 92,
    hip_max: 99,
    sleeve_length_min: 20,
    sleeve_length_max: 21,
    body_length_min: 68,
    body_length_max: 70,
  },
  {
    size_name: "L",
    size_unit: "cm",
    chest_min: 101,
    chest_max: 108,
    waist_min: 89,
    waist_max: 96,
    hip_min: 100,
    hip_max: 107,
    sleeve_length_min: 22,
    sleeve_length_max: 23,
    body_length_min: 69,
    body_length_max: 71,
  },
  {
    size_name: "XL",
    size_unit: "cm",
    chest_min: 109,
    chest_max: 118,
    waist_min: 97,
    waist_max: 106,
    hip_min: 108,
    hip_max: 116,
    sleeve_length_min: 22,
    sleeve_length_max: 23,
    body_length_min: 70,
    body_length_max: 72,
  },
  {
    size_name: "2XL",
    size_unit: "cm",
    chest_min: 119,
    chest_max: 130,
    waist_min: 107,
    waist_max: 119,
    hip_min: 117,
    hip_max: 125,
    sleeve_length_min: 22,
    sleeve_length_max: 23,
    body_length_min: 71,
    body_length_max: 73,
  },
];
