export const SizeGuidesByBrand = [
    {
        brand_name: "Gant",
        men_top: [
            {
                size_name: "XS",
                size_unit: "centimetres",
                neck: 35.5,
                chest: 98,
                waist: 98,
                hip: 98,
                back: 78,
                sleeve: 84,
            },
            {
                size_name: "S",
                size_unit: "centimetres",
                neck: 37.5,
                chest: 104,
                waist: 104,
                hip: 104,
                back: 80,
                sleeve: 87,
            },
            {
                size_name: "M",
                size_unit: "centimetres",
                neck: 39.5,
                chest: 110,
                waist: 110,
                hip: 110,
                back: 82,
                sleeve: 90,
            },
            {
                size_name: "L",
                size_unit: "centimetres",
                neck: 41.5,
                chest: 116,
                waist: 116,
                hip: 116,
                back: 84,
                sleeve: 93,
            },
            {
                size_name: "XL",
                size_unit: "centimetres",
                neck: 43.5,
                chest: 122,
                waist: 122,
                hip: 122,
                back: 86,
                sleeve: 96,
            },
            {
                size_name: "XXL",
                size_unit: "centimetres",
                neck: 45.5,
                chest: 128,
                waist: 128,
                hip: 128,
                back: 88,
                sleeve: 99,
            },
            {
                size_name: "XXXL",
                size_unit: "centimetres",
                neck: 47.5,
                chest: 134,
                waist: 136,
                hip: 136,
                back: 90,
                sleeve: 101,
            },
            {
                size_name: "4XL",
                size_unit: "centimetres",
                neck: 49.5,
                chest: 142,
                waist: 144,
                hip: 144,
                back: 92,
                sleeve: 103,
            },
        ],
        women_top: [
            {
                size_name: "XS",
                size_unit: "centimetres",
                chest: 90,
                waist: 88,
                hip: 88,
                back: 65,
                sleeve: 60,
            },
            {
                size_name: "S",
                size_unit: "centimetres",
                chest: 94,
                waist: 92,
                hip: 92,
                back: 66,
                sleeve: 60.5,
            },
            {
                size_name: "M",
                size_unit: "centimetres",
                chest: 102,
                waist: 100,
                hip: 100,
                back: 68,
                sleeve: 61.5,
            },
            {
                size_name: "L",
                size_unit: "centimetres",
                chest: 106,
                waist: 104,
                hip: 104,
                back: 69,
                sleeve: 62,
            },
            {
                size_name: "XL",
                size_unit: "centimetres",
                chest: 114,
                waist: 112,
                hip: 112,
                back: 71,
                sleeve: 63,
            },
            {
                size_name: "XXL",
                size_unit: "centimetres",
                chest: 122,
                waist: 120,
                hip: 120,
                back: 73,
                sleeve: 63.5,
            },
        ]
    },
    {
        brand_name: "dk active",
        men_top: [],
        women_top: [
            {
                size_name: "XS",
                size_unit: "centimetres",
                chest: 75,
                waist: 60,
                hip: 87,
            },
            {
                size_name: "S",
                size_unit: "centimetres",
                chest: 80,
                waist: 65,
                hip: 93,
            },
            {
                size_name: "M",
                size_unit: "centimetres",
                chest: 86,
                waist: 70,
                hip: 99,
            },
            {
                size_name: "L",
                size_unit: "centimetres",
                chest: 92,
                waist: 75,
                hip: 105,
            },
            {
                size_name: "XL",
                size_unit: "centimetres",
                chest: 98,
                waist: 80,
                hip: 111,
            },
            {
                size_name: "XXL",
                size_unit: "centimetres",
                chest: 104,
                waist: 85,
                hip: 117,
            },
            {
                size_name: "3XL",
                size_unit: "centimetres",
                chest: 115,
                waist: 94,
                hip: 123,
            },
            {
                size_name: "4XL",
                size_unit: "centimetres",
                chest: 123,
                waist: 103,
                hip: 131,
            },
            {
                size_name: "5XL",
                size_unit: "centimetres",
                chest: 131,
                waist: 112,
                hip: 139,
            },
            {
                size_name: "6XL",
                size_unit: "centimetres",
                chest: 139,
                waist: 121,
                hip: 147,
            },
        ]
    },
]